[package]
name = "quadkey"
description = "Quadkey conversion utlities"
version = "0.1.0"
edition = "2021"
homepage = "https://github.com/blacha/quadkey-rs"
repository = "https://github.com/blacha/quadkey-rs.git"
license = "MIT"
readme = "README.md"

[dependencies]
